In [1]:
import numpy as np

In [7]:
first_np_array = np.array([1, 2, 3])
first_np_array
print('first_np_array', type(first_np_array))
list1 = [4,5,6]
scnd_array  = np.array(list1)
print('scnd_array', type(scnd_array))

first_np_array <class 'numpy.ndarray'>
scnd_array <class 'numpy.ndarray'>


In [21]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
np_matrix = np.array(matrix)
print(np_matrix)
print('matrix', type(matrix), matrix)
print('np_matrix', type(np_matrix), np_matrix)
print('np_matrix[0]', np_matrix[0])
print('np_matrix[0][0]', np_matrix[0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix <class 'list'> [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
np_matrix[0] [1 2 3]
np_matrix[0][0] 1


In [30]:
l1 = [x for x in range(10)]
print(l1)
l2 = np.arange(0, 10)
print(l2)
l2 = np.arange(0.1, 0.5 + 0.1, 0.1)
print(l2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5]


In [40]:
print(np.zeros(5, dtype=int))
print(np.zeros(5))
# [[1, 2, 3], [4, 5, 6]]
# [1,2,3][4,5,6] 'C'
# [1,4][2,5][3,6] 'F'
print(np.zeros(shape=(2,5)))  

[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
lin_array = np.linspace(0, 10, 3, dtype=int)
print(lin_array)
lin_array_f = np.linspace(0.1, 9, 5)
print(lin_array_f)

[ 0  5 10]
[0.1   2.325 4.55  6.775 9.   ]


In [84]:
print('0 - 0.9999:\n', np.random.rand())  # 0-0.999
random_array = np.random.rand(2, 5)
print('np.random.rand(2, 5):\n', random_array)

0 - 0.9999:
 0.42468265986077003
np.random.rand(2, 5):
 [[0.04636625 0.66022027 0.18131422 0.16283216 0.31424576]
 [0.76156137 0.18016306 0.17476271 0.8053319  0.30666027]]


In [241]:
random_int = np.random.randint(10, 21, (3, 4))
print(random_int)
random_array = np.random.rand(2, 5)
print((random_array * 10 ) + 10)

[[13 10 18 15]
 [16 10 19 14]
 [18 19 19 20]]
[[19.34604435 11.89955741 13.79133153 17.32624935 11.96611249]
 [15.99217493 16.07824537 17.71672946 19.39667566 14.74442338]]


In [330]:
np.random.seed(2)
rand_array = np.random.randint(0, 101, (1, 10))
print(rand_array)

[[40 15 72 22 43 82 75  7 34 49]]


In [348]:
numpy_arr = np.arange(1, 15 + 1)
print(numpy_arr)
reshapred = numpy_arr.reshape(3, 5)
print(reshapred)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [364]:
np.random.seed(9)
rand_array = np.random.randint(0, 101, 10)
print(rand_array)
print(' ', np.arange(0, 10))
print('max', rand_array.max())  # max
print('min', rand_array.min())  # min
print('argmax', rand_array.argmax())
print('argmin', rand_array.argmin())
print('shape', rand_array.shape)  # shape of the array

[92 54 56 22 65 22 52 59 40 91]
  [0 1 2 3 4 5 6 7 8 9]
max 92
min 22
argmax 0
argmin 3
shape (10,)


In [378]:
np.random.seed(9)
rand_array = np.random.randint(0, 10, 10)
print(rand_array)
print(np.arange(0, 10), ' index \n')
print('rand_array[:7]  ', rand_array[:7])
print('rand_array[:7:3]', rand_array[:7:3])
print('rand_array[::-1]', rand_array[::-1])
print('rand_array[-1]  ', rand_array[-1])

[5 6 8 6 1 6 4 8 1 8]
[0 1 2 3 4 5 6 7 8 9]  index 

rand_array[:7]   [5 6 8 6 1 6 4]
rand_array[:7:3] [5 6 4]
rand_array[::-1] [8 1 8 4 6 1 6 8 6 5]
rand_array[-1]   8


In [388]:
arr = np.random.randint(0, 10, (3, 5))
print(arr, '\n')
print('arr[2][4]', arr[2][4])
# print('arr[10]', arr[10])  # Error there is no line 10
print('arr[0]', arr[0])
print('arr[0][::-1]', arr[0][::-1])

[[8 8 6 8 1]
 [7 0 1 3 6]
 [2 0 7 4 2]] 

arr[2][4] 2
arr[0] [8 8 6 8 1]
arr[0][::-1] [1 8 6 8 8]
