In [1]:
import numpy as np

In [7]:
first_np_array = np.array([1, 2, 3])
first_np_array
print('first_np_array', type(first_np_array))
list1 = [4,5,6]
scnd_array  = np.array(list1)
print('scnd_array', type(scnd_array))

first_np_array <class 'numpy.ndarray'>
scnd_array <class 'numpy.ndarray'>


In [21]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
np_matrix = np.array(matrix)
print(np_matrix)
print('matrix', type(matrix), matrix)
print('np_matrix', type(np_matrix), np_matrix)
print('np_matrix[0]', np_matrix[0])
print('np_matrix[0][0]', np_matrix[0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix <class 'list'> [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
np_matrix[0] [1 2 3]
np_matrix[0][0] 1


In [30]:
l1 = [x for x in range(10)]
print(l1)
l2 = np.arange(0, 10)
print(l2)
l2 = np.arange(0.1, 0.5 + 0.1, 0.1)
print(l2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5]


In [40]:
print(np.zeros(5, dtype=int))
print(np.zeros(5))
# [[1, 2, 3], [4, 5, 6]]
# [1,2,3][4,5,6] 'C'
# [1,4][2,5][3,6] 'F'
print(np.zeros(shape=(2,5)))  

[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
lin_array = np.linspace(0, 10, 3, dtype=int)
print(lin_array)
lin_array_f = np.linspace(0.1, 9, 5)
print(lin_array_f)

[ 0  5 10]
[0.1   2.325 4.55  6.775 9.   ]


In [84]:
print('0 - 0.9999:\n', np.random.rand())  # 0-0.999
random_array = np.random.rand(2, 5)
print('np.random.rand(2, 5):\n', random_array)

0 - 0.9999:
 0.42468265986077003
np.random.rand(2, 5):
 [[0.04636625 0.66022027 0.18131422 0.16283216 0.31424576]
 [0.76156137 0.18016306 0.17476271 0.8053319  0.30666027]]


In [239]:
random_int = np.random.randint(10, 21, (3, 4))
print(random_int)
random_array = np.random.rand(2, 5)
print((random_array * 10 ) + 10)

[[19 13 10 16]
 [17 15 13 18]
 [17 18 15 20]]
[[19.63928863 13.11329733 10.06257718 15.68202723 10.47464185]
 [19.24209132 12.04561147 11.16380617 11.43796832 10.17169832]]
